name: Build datapackage

on:
  push:
  schedule:
    - cron:  '10 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run dataflow
      run: |
        python donnees_hospitalieres_covid19.py

    - name: Push generated data
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.email "actions@github.com"
        git config user.name "actions-user"
        git add donnees-hospitalieres-covid19.zip
        git add donnees-hospitalieres-covid19
        git commit -am "New data at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        git push origin master